# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'synthesia_translator.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filePathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLine.setText("")
        self.filePathLine.setObjectName("filePathLine")
        self.gridLayout_2.addWidget(self.filePathLine, 0, 0, 1, 1)
        self.fileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileBrowseButton.setObjectName("fileBrowseButton")
        self.gridLayout_2.addWidget(self.fileBrowseButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.videoView = QtWidgets.QGraphicsView(self.centralwidget)
        self.videoView.setObjectName("videoView")
        self.verticalLayout_2.addWidget(self.videoView)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calculateKeysButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateKeysButton.setObjectName("calculateKeysButton")
        self.horizontalLayout_2.addWidget(self.calculateKeysButton)
        self.transcribeVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.transcribeVideoButton.setObjectName("transcribeVideoButton")
        self.horizontalLayout_2.addWidget(self.transcribeVideoButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Synthesia Tutorial Translator"))
        self.fileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.calculateKeysButton.setText(_translate("MainWindow", "Calculate Key Locations"))
        self.transcribeVideoButton.setText(_translate("MainWindow", "Transcribe Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
