# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\synthesia_translator\ui\advanced_options.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AdvancedOptions(object):
    def setupUi(self, AdvancedOptions):
        AdvancedOptions.setObjectName("AdvancedOptions")
        AdvancedOptions.resize(401, 317)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AdvancedOptions)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(0, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.keyOffsetLabel = QtWidgets.QLabel(AdvancedOptions)
        self.keyOffsetLabel.setObjectName("keyOffsetLabel")
        self.gridLayout.addWidget(self.keyOffsetLabel, 0, 0, 1, 1)
        self.keyDifferenceThresholdSpinBox = QtWidgets.QSpinBox(AdvancedOptions)
        self.keyDifferenceThresholdSpinBox.setMinimum(1)
        self.keyDifferenceThresholdSpinBox.setMaximum(244)
        self.keyDifferenceThresholdSpinBox.setObjectName("keyDifferenceThresholdSpinBox")
        self.gridLayout.addWidget(self.keyDifferenceThresholdSpinBox, 1, 1, 1, 1)
        self.keyOffsetSpinBox = QtWidgets.QSpinBox(AdvancedOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyOffsetSpinBox.sizePolicy().hasHeightForWidth())
        self.keyOffsetSpinBox.setSizePolicy(sizePolicy)
        self.keyOffsetSpinBox.setWrapping(False)
        self.keyOffsetSpinBox.setMaximum(100)
        self.keyOffsetSpinBox.setProperty("value", 90)
        self.keyOffsetSpinBox.setObjectName("keyOffsetSpinBox")
        self.gridLayout.addWidget(self.keyOffsetSpinBox, 0, 1, 1, 1)
        self.keyDifferenceThresholdLabel = QtWidgets.QLabel(AdvancedOptions)
        self.keyDifferenceThresholdLabel.setObjectName("keyDifferenceThresholdLabel")
        self.gridLayout.addWidget(self.keyDifferenceThresholdLabel, 1, 0, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.startingKeyNoteLabel = QtWidgets.QLabel(AdvancedOptions)
        self.startingKeyNoteLabel.setObjectName("startingKeyNoteLabel")
        self.gridLayout_2.addWidget(self.startingKeyNoteLabel, 0, 0, 1, 1)
        self.startingKeyNoteComboBox = QtWidgets.QComboBox(AdvancedOptions)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.startingKeyNoteComboBox.sizePolicy().hasHeightForWidth())
        self.startingKeyNoteComboBox.setSizePolicy(sizePolicy)
        self.startingKeyNoteComboBox.setObjectName("startingKeyNoteComboBox")
        self.gridLayout_2.addWidget(self.startingKeyNoteComboBox, 0, 1, 1, 1)
        self.verticalLayout_3.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout_3)
        self.buttonBox = QtWidgets.QDialogButtonBox(AdvancedOptions)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_2.addWidget(self.buttonBox)

        self.retranslateUi(AdvancedOptions)
        self.buttonBox.accepted.connect(AdvancedOptions.accept) # type: ignore
        self.buttonBox.rejected.connect(AdvancedOptions.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(AdvancedOptions)

    def retranslateUi(self, AdvancedOptions):
        _translate = QtCore.QCoreApplication.translate
        AdvancedOptions.setWindowTitle(_translate("AdvancedOptions", "Advanced Options"))
        self.keyOffsetLabel.setText(_translate("AdvancedOptions", "Key Read Offset [% from bottom]"))
        self.keyDifferenceThresholdLabel.setText(_translate("AdvancedOptions", "Key Difference Threshold"))
        self.startingKeyNoteLabel.setText(_translate("AdvancedOptions", "Starting Key / Note"))
