# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\synthesia_translator\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.filePathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLine.setText("")
        self.filePathLine.setReadOnly(True)
        self.filePathLine.setObjectName("filePathLine")
        self.gridLayout_2.addWidget(self.filePathLine, 0, 0, 1, 1)
        self.fileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileBrowseButton.setObjectName("fileBrowseButton")
        self.gridLayout_2.addWidget(self.fileBrowseButton, 0, 1, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_2)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.videoLabel.sizePolicy().hasHeightForWidth())
        self.videoLabel.setSizePolicy(sizePolicy)
        self.videoLabel.setMouseTracking(True)
        self.videoLabel.setScaledContents(True)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.verticalLayout_2.addWidget(self.videoLabel)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(7)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.calculateKeysButton = QtWidgets.QPushButton(self.centralwidget)
        self.calculateKeysButton.setEnabled(False)
        self.calculateKeysButton.setObjectName("calculateKeysButton")
        self.horizontalLayout_2.addWidget(self.calculateKeysButton)
        self.advancedOptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.advancedOptionsButton.setObjectName("advancedOptionsButton")
        self.horizontalLayout_2.addWidget(self.advancedOptionsButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.transcribeVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.transcribeVideoButton.setEnabled(False)
        self.transcribeVideoButton.setObjectName("transcribeVideoButton")
        self.verticalLayout_2.addWidget(self.transcribeVideoButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Synthesia Tutorial Translator"))
        self.fileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.videoLabel.setText(_translate("MainWindow", "Select Video File to Preview"))
        self.calculateKeysButton.setText(_translate("MainWindow", "Calculate Key Locations"))
        self.advancedOptionsButton.setText(_translate("MainWindow", "Advanced Options"))
        self.transcribeVideoButton.setText(_translate("MainWindow", "Transcribe Video"))
