# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'e:\synthesia_translator\ui\main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1325, 734)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.mainVerticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.mainVerticalLayout.setObjectName("mainVerticalLayout")
        self.filePickerLayout = QtWidgets.QGridLayout()
        self.filePickerLayout.setObjectName("filePickerLayout")
        self.filePathLine = QtWidgets.QLineEdit(self.centralwidget)
        self.filePathLine.setReadOnly(True)
        self.filePathLine.setObjectName("filePathLine")
        self.filePickerLayout.addWidget(self.filePathLine, 0, 0, 1, 1)
        self.fileBrowseButton = QtWidgets.QPushButton(self.centralwidget)
        self.fileBrowseButton.setObjectName("fileBrowseButton")
        self.filePickerLayout.addWidget(self.fileBrowseButton, 0, 1, 1, 1)
        self.mainVerticalLayout.addLayout(self.filePickerLayout)
        self.videoLogRow = QtWidgets.QHBoxLayout()
        self.videoLogRow.setObjectName("videoLogRow")
        self.videoLabel = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.videoLabel.sizePolicy().hasHeightForWidth())
        self.videoLabel.setSizePolicy(sizePolicy)
        self.videoLabel.setScaledContents(True)
        self.videoLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.videoLabel.setObjectName("videoLabel")
        self.videoLogRow.addWidget(self.videoLabel)
        self.logOutput = QtWidgets.QPlainTextEdit(self.centralwidget)
        self.logOutput.setReadOnly(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.logOutput.sizePolicy().hasHeightForWidth())
        self.logOutput.setSizePolicy(sizePolicy)
        self.logOutput.setMinimumSize(QtCore.QSize(250, 0))
        self.logOutput.setObjectName("logOutput")
        self.videoLogRow.addWidget(self.logOutput)
        self.mainVerticalLayout.addLayout(self.videoLogRow)
        self.buttonRow = QtWidgets.QHBoxLayout()
        self.buttonRow.setObjectName("buttonRow")
        self.previewKeysButton = QtWidgets.QPushButton(self.centralwidget)
        self.previewKeysButton.setEnabled(False)
        self.previewKeysButton.setObjectName("previewKeysButton")
        self.buttonRow.addWidget(self.previewKeysButton)
        self.advancedOptionsButton = QtWidgets.QPushButton(self.centralwidget)
        self.advancedOptionsButton.setObjectName("advancedOptionsButton")
        self.buttonRow.addWidget(self.advancedOptionsButton)
        self.mainVerticalLayout.addLayout(self.buttonRow)
        self.transcribeVideoButton = QtWidgets.QPushButton(self.centralwidget)
        self.transcribeVideoButton.setEnabled(False)
        self.transcribeVideoButton.setObjectName("transcribeVideoButton")
        self.mainVerticalLayout.addWidget(self.transcribeVideoButton)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Synthesia Tutorial Translator"))
        self.fileBrowseButton.setText(_translate("MainWindow", "Browse"))
        self.videoLabel.setText(_translate("MainWindow", "Select Video File to Preview"))
        self.logOutput.setPlainText(_translate("MainWindow", "Log output will appear here…"))
        self.previewKeysButton.setText(_translate("MainWindow", "Preview Key Locations"))
        self.advancedOptionsButton.setText(_translate("MainWindow", "Advanced Options"))
        self.transcribeVideoButton.setText(_translate("MainWindow", "Transcribe Video"))
